### ISSUE TITLE
[all] Cleaning the way we handle message in Sofa.

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#179]
Currently there is different ways to send messages in Sofa. Each way having its own 'side effects' leading to a different results exposed to the users. 

This issues was already partially addressed in Issue https://github.com/sofa-framework/sofa/issues/160 or PR https://github.com/sofa-framework/sofa/pull/106 and others.... 

The general goal of this Issue is to finally have only one system all around sofa to increase both code consistency and user interface behavior. 
 
Things to do to make that happen: 
 - [x] implementing a per component logging system on top of the msg_api to prove we can replace the existing error logging system. (Done in PR https://github.com/sofa-framework/sofa/pull/106).

 - [x] replace the existing logging of error it should contains:
    - removing the filling of the messages in sout.
    - removing the old string based buffer (API BREAK).
    - removing all the uses of the old message buffers and replace them with the new one (API BREAK).
    - updating the gui to use the new msghandler buffers.

- [ ] update sofaQtQuick (but there is no API break)

- [x] update runSofa to the buffer API break, at least make it compile/run

 - [x] clean the way we handle the printLog (see Issue https://github.com/sofa-framework/sofa/issues/160)
    - remove/rename the printLog data and implement backward compatibility 
    - a replacement solution has to be implement to control the printing.
    - a replacement solution has to be implement to control the messages based on a per-component selection of the printed messages

 - [ ] extending/unifying the sout/serr with more sdebug/swarning. This must be discussed seriously during a meeting because I currently made a lot of attempts to this but didn't managed to implement a working solution without the sever flawn sout/serr have. If you have ideas on that please make a branch with working proposal so that we have sounded discussion (see Issue https://github.com/sofa-framework/sofa/issues/160)

 - [x] implementing the improvement of  the msg_* API discussed in #160. 

If like me you think this should be fixed...please join this discussion and share the workload. 
I'm working in https://github.com/SofaDefrost/sofa/tree/improve-messageapi

**Comment by damienmarchal** [comment]
About a possible implementation for the following syntax:
```cpp
msg_info() << "Implicit 'this'";
msg_info(this) << "Explicit";
msg_info("Something else") << "Hep";
```

I finally have one that seems to work on gcc and on visual studio.
You can try it one-line at: http://www.cpp.sh/3xvfk

I have a question to you @matthieu-nesme, @thomas-lemaire, @nurbal . I really like the implicit version but at the same time I fear using complex MACRO trick. What do you think ? 

DM

EDIT: maybe trying it...and see if this cause troubles revert it back as it is only a chang in Messaging.h  file ?

**Comment by damienmarchal** [comment]
Almost done... the f_printLog stuff is replaced with d_msgInfoLevel. 
Backward compatibility is implemented as well as deprecation warning. 

This allow to write the follow things:
```cpp
    msg_info_when( d_msgInfoLevel.getValue() != InfoMessageLevel::MUTED ) << "I print often" ;
    msg_info_when( d_msgInfoLevel.getValue() != InfoMessageLevel::MUTED ) << "I print often" ;

**Comment by thomas-lemaire** [comment]
I like the simplicity of your proposal, however the macro trick (does it work with clang ?) could be avoided if we decide some different names for the macro, like 

msg_info () << "Implicit 'this'"; // keep that one, the most common 

msg_info_component ( this ) << "Explicit"; // or s.t. else shorter 
msg_info_name ( " Something else " ) << "Hep"; // I think that one is mostly used in python, should it be exposed in c++ as a macro ? 

thomas 

----- Mail original -----

**Comment by thomas-lemaire** [comment]
at least I would push for simplicity here, like if msgInfoLevel==InfoMessageLevel::MUTED, then no info message goes to the component stack, 
when using: 
msg_info () << "I print if I am not muted" ; 

the _when version can be kept for fine tuning (I personally find it overkill) 

thomas 

----- Mail original -----

**Comment by damienmarchal** [comment]
I agree that we should embed the 'muted' test in the macro 
msg_info() << "Emitted only when InfoMessageLevel is not Muted"...

The macro trick should work with clang (but didn't tested) so now we could vote for the version we prefer. 
@matthieu-nesme, @hugtalbot, @thomas-lemaire, @bcarrez,  @epernod, @EulalieCoevoet, @fredroy 

Which one would you prefer to use: 
```cpp 
msg_info() << "I'm a message from the 'this' component..."
msg_info(other) << "I'm a message from the 'other' component..."
msg_info("NotAComponent") << "I'm a message emitted not from a component..."
```
or
```cpp 
msg_info() << "I'm a message from the 'this' component..."
msg_info_from(other) << "I'm a message from the 'other' component..."
msg_info_from("NotAComponent") << "I'm a message emitted not from a component..."
```
or
```cpp 
msg_info() << "I'm a message from the 'this' component..."
msg_info_component(other) << "I'm a message from the 'other' component..."
msg_info_name("NotAComponent") << "I'm a message emitted not from a component..."
```
Please answer 1,2 or 3 :) 

PS1: In case you prefer something else...please explain a bit
PS2: sout/serr will be fixed independently. 
During a transitional period we should make a macro that maps sout to msg_info and serr to msg_warning.

PS 3: @thomas-lemaire  I have added the muted test to the branch.

**Comment by matthieu-nesme** [comment]
1

**Comment by hugtalbot** [comment]
1

**Comment by damienmarchal** [comment]
Hi, 

Thanks for those who voted. 

So I have implemented all that. 

To have a taste of how would look like a switch to the msg_api I have converted 300+ std::cerr from sofa and 200+ of the broken if(f_printLog.getValue()) sout << "blabha" into their equivalent msg_* 

I personally found that quite ok but please tell me if it goes in a direction you like. 

EDIT: I forgot to see that everything is in the PR #190 
EDIT 1: there is still more than 3000 std::cerr/std::cout :)

**Comment by damienmarchal** [comment]
It was a tedious work be we now have a nice API. 
It has been merged since PR 190 so please use it :) 
I close this issue.
